#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# One stage per criterion that no automated check covers. The list, and the
# reason each one is here rather than in the floor check, is in
# docs/manual-checks.md. Keep the two in step.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=14

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WS="${TUI_CHECK_WS:-${TMPDIR:-/tmp/}}"
WS="${WS%/}/tui-manual-checks"
ENV_FILE="${TUI_CHECK_RESULTS:-$REPO_ROOT/.manual-checks.env}"
REPORT="$REPO_ROOT/docs/manual-checks-results.md"

# ── helpers, below the marker so the library above stays untouched ─────────

# verdict KEY "Question" records pass / fail / skip plus a free-text note.
# Both land in ENV_FILE, so a re-run offers what you answered last time and
# you can stop half way without losing the morning.
verdict() {
  local key="$1" label="$2" v
  while :; do
    ask "$key" "  ${label} [p]ass / [f]ail / [s]kip:"
    v="$(printf '%s' "${!key}" | tr '[:upper:]' '[:lower:]')"
    case "$v" in
      p|pass) v="pass"; break ;;
      f|fail) v="fail"; break ;;
      s|skip) v="skip"; break ;;
      *) warn "gõ p, f hoặc s" ;;
    esac
  done
  write_env "$key" "$v"
  ask "${key}_NOTE" "  Ghi chú (Enter để bỏ qua):"
  local note_var="${key}_NOTE"
  write_env "$note_var" "${!note_var}"
  if [[ "$v" == "fail" ]]; then
    warn "FAIL: mở issue mới, dán đúng dòng quan sát được. Đừng sửa tại chỗ."
  fi
}

# open_doc FILE opens a workspace file in the running VS Code window.
open_doc() {
  local f="$WS/$1"
  if command -v code >/dev/null 2>&1; then
    printf '  %s↗ mở%s %s\n' "$GREEN" "$RESET" "$1"
    code -r "$f" >/dev/null 2>&1 || warn "không mở được $f"
  else
    warn "không có lệnh 'code'; mở tay: $f"
  fi
}

# ── Stage 0 is not a stage: make sure there is something to test against ───

banner "Bản kiểm tay TUI Markdown 2.17"

if [[ ! -f "$WS/test.md" ]]; then
  _clear
  printf '\n%s%s  Dựng workspace test%s\n\n' "$BOLD" "$BLUE" "$RESET"
  say "Chưa có workspace, đang dựng tại:"
  note "  $WS"
  mkdir -p "$WS/images"
  cp "$REPO_ROOT/media/icon.png" "$WS/images/sample-image.png" 2>/dev/null || true
  cp "$REPO_ROOT/media/icon.png" "$WS/images/shared-image.png" 2>/dev/null || true
  mkdir -p "$WS/.vscode"
  printf '{\n  "[markdown]": { "editor.tabSize": 2, "editor.insertSpaces": true }\n}\n' \
    > "$WS/.vscode/settings.json"
  cat > "$WS/test.md" <<'MD'
# Heading One

Some **bold** text and a [link](https://example.com).

| Column A | Column B | Column C |
| -------- | -------- | -------- |
| 1        | 2        | 3        |
| 4        | 5        | 6        |

- mục cha
  - mục con
    - mục cháu

![ảnh riêng](images/sample-image.png)

![ảnh dùng chung](images/shared-image.png)

[[chua-co-file-nay]]
MD
  printf '# Tài liệu thứ hai\n\n![dùng chung](images/shared-image.png)\n' > "$WS/other.md"
  : > "$WS/long.md"
  printf '# File dài\n\n' >> "$WS/long.md"
  for i in $(seq 1 200); do
    printf 'Đoạn %s. Cuộn xuống giữa file rồi đóng tab, mở lại phải về đúng chỗ.\n\n' "$i" >> "$WS/long.md"
  done
  say "Xong."
  pause "Enter để mở VS Code với extension"
  ( cd "$REPO_ROOT" && npm run build >/dev/null 2>&1 ) || warn "npm run build lỗi; đang dùng bản out/ cũ"
  env -u ELECTRON_RUN_AS_NODE -u VSCODE_IPC_HOOK -u VSCODE_IPC_HOOK_CLI -u VSCODE_PID \
    code --new-window --extensionDevelopmentPath="$REPO_ROOT" "$WS" >/dev/null 2>&1 &
  sleep 6
fi

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "A1b: Enter kích hoạt một mục trong menu bảng (#118)"
say "Đây là ĐÚNG lỗi #118 đã sửa: trước đó menu bắt mousedown nên Enter không làm gì."
note "Floor check đã nhận phần mở menu, roving focus và Escape. Enter thì không:"
note "ProseMirror không nhận selection khi view của nó không giữ tiêu điểm."
open_doc "test.md"
step "Chuột phải vào một ô bất kỳ của bảng."
step "Nhấn mũi tên xuống tới khi tiêu điểm nằm ở 'Align Column Left'."
step "Nhấn Enter."
say "ĐẠT nếu: cột đó căn trái ngay, và menu đóng lại."
verdict A1B "A1b"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "A2: Ctrl/Cmd+Shift+M chạy từ CẢ HAI phía (#108)"
note "Floor chỉ kiểm được hai lệnh CÓ ĐĂNG KÝ, không kiểm được phím tắt thật."
step "Cmd+K Cmd+S để mở Keyboard Shortcuts, gõ 'TUI'."
step "Phải thấy CẢ HAI: 'View Source' và 'View Rich Text (WYSIWYG)', cùng Cmd+Shift+M."
step "Quay lại test.md, bấm Cmd+Shift+M: phải sang source view."
step "Đang ở source view, bấm Cmd+Shift+M lần nữa: phải quay lại WYSIWYG."
say "Chiều thứ hai là chiều trước #108 KHÔNG có đường về ngoài icon thanh tiêu đề."
verdict A2 "A2"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "A3b: Bubble menu ở zoom DƯỚI 100% (#116)"
note "Floor đã đo ở zoom 1.2: dx=0 dy=44. Dưới 100% thì chưa ai đo."
open_doc "test.md"
step "Bấm Cmd+- hai lần (xuống khoảng 80%)."
step "Bôi đen cụm chữ in đậm ở dòng đầu."
say "ĐẠT nếu: bubble menu hiện NGAY CẠNH vùng chọn, không lệch xuống hay sang phải."
step "Bấm thử nút Bold: phải tác động đúng vùng đang chọn."
step "Cmd+0 để về 100%."
verdict A3B "A3b"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "B1: Gõ rồi đóng tab trong 300 ms, 10 lần (#104)"
warn "Bằng chứng cũ cho mục này là một kịch bản mô phỏng chạy NGOÀI repo, không commit."
note "Coi như chưa từng kiểm. Đây là mục về MẤT DỮ LIỆU."
open_doc "long.md"
step "Gõ 5 ký tự vào cuối file rồi bấm Cmd+W NGAY (dưới 300 ms)."
step "Mở lại long.md, xem 5 ký tự còn không."
step "Lặp đủ 10 lần và ĐẾM số lần còn nguyên."
say "ĐẠT nếu: 10/10. Bất cứ số nào nhỏ hơn là fail, ghi con số vào ghi chú."
verdict B1 "B1"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "B2: Nhớ vị trí con trỏ và cuộn theo từng file (#121)"
note "Lưu ở workspaceState của extension host, KHÔNG ở vscode.setState()."
note "Webview này không bật retainContextWhenHidden: ẩn tab là webview bị huỷ."
open_doc "long.md"
step "Cuộn xuống khoảng giữa, đặt con trỏ vào một đoạn nhận ra được."
step "Đóng tab, mở lại: phải đúng chỗ cũ, cả cuộn lẫn con trỏ."
step "Mở test.md ở vị trí khác, qua lại hai file: mỗi file nhớ riêng."
step "Đóng hẳn VS Code, mở lại workspace: vị trí phải còn đó."
say "Bước cuối là chỗ workspaceState khác setState, và là lý do chọn nó."
verdict B2 "B2"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "C1: Clipboard lỗi thì có báo, không im lặng (#105)"
note "Trước #105 nó thất bại không kêu một tiếng."
step "Copy một đoạn CHỮ rồi dán vào editor: phải ra chữ, bình thường."
step "Ép lỗi đọc clipboard ảnh (copy một định dạng ảnh lạ, hoặc chặn quyền)."
say "Cái cần thấy là MỘT TOAST LỖI, không phải im lặng tuyệt đối."
warn "Không ép được lỗi thì chọn [s]kip và ghi lý do. ĐỪNG chọn pass."
verdict C1 "C1"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "C2: Dán ảnh (#88)"
open_doc "test.md"
step "Chụp màn hình vào clipboard: Cmd+Ctrl+Shift+4."
step "Dán vào editor."
say "ĐẠT nếu cả ba: ảnh hiện trong tài liệu, có file mới trong images/,"
say "và markdown ở source view trỏ đúng đường dẫn tương đối đó."
verdict C2 "C2"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "C3: Đổi tên đường dẫn ảnh thì file trên đĩa đổi theo (#88)"
note "Cần tuiMarkdown.autoRenameImages đang bật (mặc định bật)."
open_doc "test.md"
step "Double-click vào ảnh vừa dán, sửa TÊN FILE trong đường dẫn, lưu."
step "Xem thư mục images/: file phải ĐỔI TÊN, không phải sinh ra file thứ hai."
step "Thử đổi cả THƯ MỤC: thao tác này cố ý bị từ chối."
say "ĐẠT nếu: đổi tên trong cùng thư mục thì chạy, đổi thư mục thì không."
verdict C3 "C3"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "C4b: Ảnh bị xoá có THẬT SỰ vào Thùng rác không (#88, #126)"
warn "Đây là mục đáng nhất trong cả bản kiểm."
note "Floor đã chứng minh file BIẾN MẤT khi lưu, nhưng đo được foundIn~/.Trash=no."
note "Mô tả setting thì hứa Trash. Một extension-test host không phải bằng chứng"
note "về máy anh, nên câu trả lời nằm ở đây."
open_doc "test.md"
step "Xoá dòng ![ảnh riêng](images/sample-image.png), rồi Cmd+S."
step "Mở Thùng rác: sample-image.png có ở đó không?"
say "ĐẠT nếu: file nằm trong Thùng rác và khôi phục được."
say "FAIL nếu: file biến mất hẳn. Đó là issue thứ 5, và nó khác #126."
step "Rồi xoá tiếp dòng ảnh dùng chung, Cmd+S, trong khi other.md vẫn dùng nó."
note "Nó sẽ bị xoá không hỏi gì. Đó là #126, đã biết, không cần mở issue mới."
verdict C4B "C4b"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "E1b: Chèn bằng Enter, và lời mời tạo file (#123)"
note "Floor đã nhận phần popup liệt kê file. Phần chèn thì chưa."
open_doc "test.md"
step "Gõ @ giữa một đoạn, gõ thêm vài ký tự, mũi tên chọn, Enter."
step "Xem source view: phải là một link markdown đúng cú pháp."
step "Bấm vào wiki link [[chua-co-file-nay]] ở cuối file."
say "ĐẠT nếu: hiện toast 'not found. Create it?' kèm nút Create,"
say "bấm Create thì file rỗng được tạo CẠNH tài liệu và mở ra."
step "Thử [[../ngoài-thư-mục]]: KHÔNG được mời tạo, chỉ báo not found."
verdict E1B "E1b"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "F1: editor.tabSize đổi thì thụt lề editor ghi ra đổi theo (#102)"
note "tuiMarkdown.listIndent mặc định 'editor', tức bám editor.tabSize cho markdown."
open_doc ".vscode/settings.json"
step "Đổi editor.tabSize trong [markdown] thành 4, lưu."
step "Quay lại test.md, sửa một chữ trong danh sách lồng, lưu, xem source."
say "Thụt phải là 4 dấu cách."
step "Đổi về 2, sửa lại, lưu: thụt thành 2."
step "Lưu lần THỨ HAI mà không sửa gì: nội dung KHÔNG được đổi thêm."
say "Bước cuối chính là lỗi #102 báo: dòng nối thụt bằng tab tách khỏi item"
say "của nó ở lần lưu thứ hai."
verdict F1 "F1"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "G1: Ảnh chụp trước và sau ở hai theme (#86)"
note "#86 dời 2356 dòng CSS ra editor.css và tuyên bố KHÔNG đổi một declaration nào."
note "Không lưới tự động nào kiểm được tuyên bố đó. Chỉ có mắt."
open_doc "test.md"
step "Mở panel Appearance, chọn theme SÁNG (Frame), chụp màn hình."
step "Đổi sang theme TỐI tương ứng (Frame Dark), chụp màn hình."
step "Soát: heading, bảng, code block, alert, task list, ảnh, mục lục, thanh công cụ."
step "Đổi qua đủ 12 theme một lượt."
say "ĐẠT nếu: không theme nào vỡ layout hoặc mất màu chữ."
verdict G1 "G1"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "X1: Git Graph mở diff .md (#48)"
note "#122 chữa việc MỞ file và điều đó ĐÃ có bằng chứng tự động."
note "Diff editor là một đường KHÁC trong VS Code, floor workspace không cài Git Graph."
step "Cài Git Graph, bấm vào một commit có sửa file .md, xem diff."
say "ĐẠT nếu: diff mở bằng text editor thường."
warn "Nếu diff vẫn mở bằng WYSIWYG: đó là defect KHÁC #122. Mở issue MỚI,"
warn "đừng mở lại #48."
verdict X1 "X1"

# ── 14 ────────────────────────────────────────────────────────────────────
stage "X2: Các menu TRÔNG như thế nào"
note "Floor khẳng định menu hiện ra và đúng số mục. Nó không nói gì về đẹp xấu."
open_doc "test.md"
step "Xem lần lượt: menu slash (gõ /), bubble menu, link popover,"
step "menu chuột phải bảng, lightbox (double-click ảnh)."
step "Ở CẢ theme sáng và tối."
say "Soát: canh lề, khoảng cách, màu chữ trên nền, trạng thái hover."
verdict X2 "X2"

# ── Kết quả ───────────────────────────────────────────────────────────────

_clear
{
  printf '# Kết quả bản kiểm tay\n\n'
  printf 'Ngày: %s  ·  Phiên bản: %s  ·  VS Code: %s\n\n' \
    "$(date +%Y-%m-%d)" \
    "$(node -p "require('$REPO_ROOT/package.json').version" 2>/dev/null || echo '?')" \
    "$(code --version 2>/dev/null | head -1 || echo '?')"
  printf 'Sinh bởi `scripts/manual-checks.sh`. Tiêu chí và lý do từng mục nằm ở\n'
  printf '`docs/manual-checks.md`.\n\n'
  printf '| Mục | Kết quả | Ghi chú |\n| --- | --- | --- |\n'
  for k in A1B A2 A3B B1 B2 C1 C2 C3 C4B E1B F1 G1 X1 X2; do
    v=$(grep -E "^${k}=" "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
    n=$(grep -E "^${k}_NOTE=" "$ENV_FILE" | tail -n1 | cut -d= -f2- || true)
    printf '| %s | %s | %s |\n' "$k" "${v:-chưa chạy}" "${n:-}"
  done
  printf '\nMục nào `fail` thì mở issue mới, dán đúng dòng quan sát được.\n'
  printf 'Mục nào `skip` thì vẫn là nợ, không phải là xong.\n'
} > "$REPORT"

finish
note "báo cáo: $REPORT"
note "kết quả thô (chạy lại sẽ nhớ): $ENV_FILE"
printf '\n'
pass_n=$(grep -cE '^[A-Z0-9_]+=pass$' "$ENV_FILE" 2>/dev/null || true)
fail_n=$(grep -cE '^[A-Z0-9_]+=fail$' "$ENV_FILE" 2>/dev/null || true)
skip_n=$(grep -cE '^[A-Z0-9_]+=skip$' "$ENV_FILE" 2>/dev/null || true)
printf '  %spass %s%s  ·  %sfail %s%s  ·  %sskip %s%s\n\n' \
  "$GREEN" "$pass_n" "$RESET" "$RED" "$fail_n" "$RESET" "$YELLOW" "$skip_n" "$RESET"
